[package]
name = "dotsync"
version = "0.0.2"
edition = "2024"

[dependencies]
log = "=0.4.27"
env_logger = "=0.11.7"
clap = { version = "=4.5.53", features = ["derive"] }
zip = "=7.0.0"
chrono = "=0.4.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "=1.0.147"